version: "3.7"
   
services:
  db:
    image: mysql:8.0.21
    # ports:
    #   - "30000:3306"
    environment:
      - MYSQL_DATABASE=database1
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  web:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash -c "chmod +x /code/docker-entrypoint.sh && /code/docker-entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db