# Generated by Django 2.0.1 on 2019-12-01 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0002_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
