# Generated by Django 2.0.1 on 2020-07-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0004_auto_20200107_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausalDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('variables_json', models.TextField(default='[]')),
                ('causal_diagram_json', models.TextField(default='{}')),
            ],
        ),
    ]
