# Generated by Django 2.0.1 on 2020-07-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0005_causaldiagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='causaldiagram',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
