# Generated by Django 2.0.1 on 2020-08-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0006_causaldiagram_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_type',
            field=models.CharField(default='normal', max_length=100),
        ),
    ]
