# Generated by Django 2.0.1 on 2020-09-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0008_userdata_causal_survey_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='progress',
            field=models.CharField(default='created', max_length=100),
        ),
    ]
