# Generated by Django 2.0.1 on 2020-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0009_userdata_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='completion_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
