# Generated by Django 2.0.1 on 2020-09-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0010_userdata_completion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='condition',
            field=models.CharField(max_length=100),
        ),
    ]
