# Generated by Django 2.0.1 on 2020-10-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0011_auto_20200922_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='survey_response_json',
            field=models.TextField(default='{}'),
        ),
    ]
