# Generated by Django 2.0.1 on 2020-11-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0012_userdata_survey_response_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='actual_task_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='practice_task_json',
            field=models.TextField(default='{}'),
        ),
    ]
