# Generated by Django 2.0.1 on 2020-11-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0013_auto_20201112_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.TextField()),
                ('result_json', models.TextField()),
            ],
        ),
    ]
