# Generated by Django 2.0.1 on 2020-11-18 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0014_regressionresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegressionResults',
            new_name='RegressionResult',
        ),
    ]
