# Generated by Django 2.0.1 on 2020-11-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0015_auto_20201117_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='regressionresult',
            name='Xnames',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regressionresult',
            name='Yname',
            field=models.TextField(default='X'),
            preserve_default=False,
        ),
    ]
