# Generated by Django 2.0.13 on 2021-10-10 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorbot', '0016_auto_20201117_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('topic_id', models.CharField(max_length=100)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(default='')),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mentorbot.Essay')),
            ],
        ),
    ]
